# Generated by Django 6.0.1 on 2026-03-12 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('manifesto', models.TextField()),
                ('slot', models.IntegerField(choices=[(1, 'Candidate 1'), (2, 'Candidate 2')])),
                ('approved', models.BooleanField(default=False)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.party')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('party', 'class_name', 'section', 'slot')},
            },
        ),
    ]
