# Generated by Django 6.0.1 on 2026-03-12 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('candidate_start', models.DateTimeField()),
                ('candidate_end', models.DateTimeField()),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='party_symbols/')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='elections.election')),
            ],
            options={
                'unique_together': {('election', 'name')},
            },
        ),
    ]
